# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stack Half Full
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Optimistically learning data science
baseurl: "/stack-half-full" # the subpath of your site, e.g. /blog
url: "https://shielamms.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  shielamms

# Build settings
# theme: minima
# theme: jekyll-theme-hydejack  # comment out when on local
remote_theme: hydecorp/hydejack@v9.1.4  # uncomment when on github pages

plugins:
  - jekyll-feed
  - jekyll-avatar
  # - jekyll-include-cache

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

permalink: /:categories/:slug:output_ext
collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

menu:
  - title: Data Ops
    url: /dataops/
  - title: NLP
    url: /nlp/
  - title: Mathematics
    url: /maths/
  - title: Notebooks
    url: /notebooks/
  - title: 15WDS
    url: /data-project/
  - title: About
    url: /about/

kramdown:
  math_engine:         mathjax
  math_engine_opts:    {}

author:
  picture:  /assets/images/author3.jpg
  about: |
    I'm a Data Engineer at [BridgeU](https://bridge-u.com), where my work focuses on data pipelines,
    cloud infrastructure, and recommendation systems. On the side, I'm learning data science through
    mini projects and online tutorials. I'm no full-stack data scientist, but I'd like to think that
    my stack is half-full and I'm constantly learning new things.



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
