# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stack Half Full
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Code optimistically.
  Your skills are half-stack full.
baseurl: "/stack-half-full" # the subpath of your site, e.g. /blog
url: "https://shielamms.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  shielamms

# Build settings
# theme: minima
#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.1.4

plugins:
  - jekyll-feed
  - jekyll-avatar
  # - jekyll-include-cache

collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true

menu:
  - title: Data Ops
    url: /dataops/
  - title: Notebooks
    url: /notebooks/
  - title: NLP
    url: /nlp/
  - title: About
    url: /about/

author:
  picture:  /assets/images/author3.jpg
  about: |
    I'm a Data Engineer at [BridgeU](https://bridge-u.com),
    an ed-tech company that helps students find international undergraduate opportunities.
    I have dabbled in several areas of software development before
    finding my passion in the wide field of data science. My work currently focuses on data pipelines,
    cloud infrastructure, and recommendation systems.


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
